version: '3.8'
# docker-compose -f docker-compose-app-v1.0.yml up -d
services:
  # 部署前端项目
  group-buy-market-front:
    image: sweaterxjy/group-buy-market-app-front:1.0-SNAPSHOT
    container_name: group-buy-market-front
    restart: always
    ports:
      - '8090:80'
    #volumes:
    #  - ./nginx/html:/usr/share/nginx/html
    privileged: true
  # 部署后端项目
  # 原镜像，需要自己构建；fuzhengwei/group-buy-market-app:1.3
  # 代理镜像（小傅哥打包好的，可以直接使用）； registry.cn-hangzhou.aliyuncs.com/xfg-studio/group-buy-market-app:1.3
  group-buy-market:
    image: sweaterxjy/group-buy-market-app:1.0-SNAPSHOT
    #    image: fuzhengwei/group-buy-market-app:1.3
    container_name: group-buy-market-app
    restart: on-failure
    ports:
      - "8091:8091"
    environment:
      - TZ=PRC
      - SERVER_PORT=8091
      - SPRING_DATASOURCE_USERNAME=root
      - SPRING_DATASOURCE_PASSWORD=123456
      - SPRING_DATASOURCE_URL=jdbc:mysql://mysql:3306/group_buy_market?serverTimezone=UTC&characterEncoding=utf8&autoReconnect=true&serverTimezone=Asia/Shanghai
      - SPRING_DATASOURCE_DRIVER_CLASS_NAME=com.mysql.cj.jdbc.Driver
      - SPRING_HIKARI_POOL_NAME=Retail_HikariCP
      - REDIS_SDK_CONFIG_HOST=redis
      - REDIS_SDK_CONFIG_PORT=6379
    volumes:
      - ./log:/data/log
    logging:
      driver: "json-file"
      options:
        max-size: "10m"
        max-file: "3"
    networks:
      - my-network
networks:
  my-network:
    driver: bridge
